name = "Stones to Circuit"
author = "Finn"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dfaf192f3372b9f7b25b27e979b0b329981a410e1c6fb7c62cc84e4d02af28bf"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.256"
